[env] ## tells cargo make that we're in the context of a Cargo workspace
PORT = 8080

[tasks.run]
env = { "RUST_ENV" = "development", "PORT" = "${PORT}" }
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.styles]
command = "pnpm"
args = [
    "dlx",
    "tailwindcss",
    "-i",
    "./styles/tailwind.css",
    "-o",
    "./assets/main.css",
    "--watch",
]
